### ISSUE TITLE
Audio source not detected

### ISSUE THREAD

**Issue by JohnWeidner** [JohnWeidner/ScreenRecorderExtension#2]
I've seen times where when I start the extension the mic meter does not indicate that any audio input is being detected.   Restarting chrome fixes the problem.

**Comment by zombiestudio** [comment]
Can you be more detailed about this. When this is happen? Maybe some other tab used your mic and did not finish it's session?

**Comment by JohnWeidner** [comment]
This appeared to have been an incompatibility with Chrome's version 60 upgrade.   I made a change to the vumeter() setup in receiver.js that appears to have fixed this issue.
