### ISSUE TITLE
Feature Request - specify download folder

### ISSUE THREAD

**Issue by JohnWeidner** [JohnWeidner/ScreenRecorderExtension#4]
A user requests being able to specify what folder their files get downloaded to.   I wouldn't want to clutter the main user interface.   However, an "options" menu item would be ok.

**Comment by JohnWeidner** [comment]
I've noticed that chrome://settings/downloads has an option that allows you to specify where all your downloads should go or whether you should be prompted each time.   So I doubt that "a href" could alter this location.   I suspect that we'd have to write the files using some other mechanism to be able to support an option of specifying a download folder.   Maybe we could use chrome.fileSystem.

**Comment by zombiestudio** [comment]
John, as I mentioned in update at #6 

> Update:
Now I changed ourrecorder.js and manifest files and added feature according to #4
So, users will see "Save As" dialog after click on Stop recording button. Save as dialog will be filled with filename from options page (predefined filename or url).

We now use [chrome.downloads API](https://developer.chrome.com/extensions/downloads)
Please check that pull request, test it and merge.

And about [fileSystem API](https://developer.chrome.com/apps/fileSystem) it's only allowed in Chrome Apps (not in extensions), and according to [Google Apps about page](https://developer.chrome.com/apps/about_apps)

> Important: Chrome will be removing support for Chrome Apps on Windows, Mac, and Linux. Chrome OS will continue to support Chrome Apps. Additionally, Chrome and the Web Store will continue to support extensions on all platforms.

So my opinion is that this is the easiest and only true way to allow user to specify download folder and I think that there is no other way for that unless if we use some other tools (developed as custom api) which will be connected to our chrome extension. But, in case of that, I am not sure will it be accepted on Chrome webstore.

**Comment by JohnWeidner** [comment]
Current functionality of prompting user where to save seems like the best solution.
