### ISSUE TITLE
Feature Request - specify filename for download

### ISSUE THREAD

**Issue by JohnWeidner** [JohnWeidner/ScreenRecorderExtension#5]
A user would like to be able to specify the filename for their download.   Would not want to clutter the main UI.   Instead the following could be added to the "options" page.

Download as:
   ( * )  screenVideo.webm
   (   )  use domain name of site being recorded

The first option would allow user to pick the name of the file to download to.   (Extension would be required to be .webm)

The second option would inspect the browser's URL (at the time the recording is being ended) and use the the domain name (ignoring subdomain, TLD, and SLD)

**Comment by JohnWeidner** [comment]
Thanks @zombiestudio   I decided to not have the "Options" button on the "Start Recording" screen.   Users will need to right-click the extension icon to get to the options page.

**Comment by zombiestudio** [comment]
Deal. I'll removed now. Please wait a sec and after update you can accept pull request

**Comment by zombiestudio** [comment]
@JohnWeidner please check now #6 
I removed Options from popup window, so user can access via extensions page or via right click on extension icon.
